name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you need
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirenments.txt
        
      
    - name: Run pylint
      run: |
        pylint src

    - name: Run flake8
      run: |
        flake8 src
      
