name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Specify the Python version you need
    - run: pip install -r tests/requirements-test.txt

      
    - name: Run pylint
      run: |
        pylint src

    - name: Run flake8
      run: |
        flake8 src
      
