name: Lint

on:
  push:
  workflow_call:



jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # Specify the Python version you need
    - run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements-test.txt

    - name: Run pylint
      run: |
        pylint src --fail-under=9.9

    - name: Run flake8
      run: |
        flake8 src
      
